# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [68]:
import pandas as pd
from plotly import express, graph_objects

# Notebook Presentation

In [69]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [70]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [71]:
# Challenge: How many rows and columns does df_apps have? 
df_apps.shape

(10841, 12)

In [72]:
# What are the column names? 
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='str')

In [73]:
# What does the data look like? 
df_apps.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up

In [74]:
# Look at a random sample of 5 different rows with .sample()
df_apps.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
6170,Map and Router Badge,MAPS_AND_NAVIGATION,4.40,3652,32.00,"500,000",Free,0,Everyone,Maps & Navigation,"July 25, 2018",4.1 and up
1753,Qu'est ce qui est jaune et qui attend ?,FAMILY,NaN,10,3.00,500,Free,0,Everyone,Entertainment,"July 13, 2017",4.4 and up
8555,Ghost Detector,FAMILY,3.50,35337,7.40,"5,000,000",Free,0,Teen,Entertainment,"May 25, 2018",4.0 and up
6788,WannaMeet – Dating & Chat App,DATING,4.10,6701,11.00,"1,000,000",Free,0,Mature 17+,Dating,"June 29, 2018",4.0.3 and up
10100,Lep's World 🍀,GAME,4.30,696019,36.00,"50,000,000",Free,0,Everyone 10+,Arcade,"May 26, 2018",4.1 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [75]:
df_apps.drop(labels=['Android_Ver', 'Last_Updated'], axis=1, inplace=True)
df_apps.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [76]:
nan_rows = df_apps[df_apps.Rating.isna()]
nan_rows.shape

(1474, 10)

In [77]:
df_apps_clean = df_apps.dropna()
df_apps_clean.shape

(9367, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [78]:
# Check for duplicates
df_apps_clean.duplicated().value_counts()
duplicated_rows = df_apps_clean[df_apps_clean.duplicated()]

print(duplicated_rows.shape)
duplicated_rows.head()

(476, 10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
946,420 BZ Budeze Delivery,MEDICAL,5.00,2,11.00,100,Free,0,Mature 17+,Medical
1133,MouseMingle,DATING,2.70,3,3.90,100,Free,0,Mature 17+,Dating
1196,"Cardiac diagnosis (heart rate, arrhythmia)",MEDICAL,4.40,8,6.50,100,Paid,$12.99,Everyone,Medical
1231,Sway Medical,MEDICAL,5.00,3,22.00,100,Free,0,Everyone,Medical
1247,Chat Kids - Chat Room For Kids,DATING,4.70,6,4.90,100,Free,0,Mature 17+,Dating

In [79]:
# Instagram entries
df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [80]:
# We need to provide the column names that should be used in the comparison to identify 
# duplicates
# If we do this (drop_duplicates) without specifying how to identify duplicates, we see 
# that 3 copies of Instagram are retained because they have a different number of reviews. 
# We need to provide the column names that should be used in the comparison to identify 
# duplicates.

df_apps_clean.drop_duplicates(inplace=True, subset=['App', 'Type', 'Price'])
df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social

In [81]:
df_apps_clean.shape

(8199, 10)

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [82]:
# Challenge: Identify which apps are the highest rated. What problem might you encounter 
# if you rely exclusively on ratings alone to determine the quality of an app?
# 1.st approach
highest_rating = df_apps_clean[df_apps_clean.Rating == df_apps_clean.Rating.max()]
highest_rating

# 2nd approach
df_apps_clean.sort_values(by='Rating', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
1751,Spine- The dating app,DATING,5.00,5,9.30,500,Free,0,Teen,Dating
1761,Selfie With Champion AJ Style,PHOTOGRAPHY,5.00,2,7.50,500,Free,0,Everyone,Photography
1763,Ag Valley Cooperative,BUSINESS,5.00,6,74.00,500,Free,0,Everyone,Business
1769,Yazdani Cd Center EllahAbad Official App,FAMILY,5.00,8,3.80,500,Free,0,Everyone,Entertainment

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [83]:
df_apps_clean.sort_values(by="Size_MBs", ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
8719,Draft Simulator for FUT 18,SPORTS,4.60,162933,100.00,"5,000,000",Free,0,Everyone,Sports
8718,Mini Golf King - Multiplayer Game,GAME,4.50,531458,100.00,"5,000,000",Free,0,Everyone,Sports
10295,SimCity BuildIt,FAMILY,4.50,4218587,100.00,"50,000,000",Free,0,Everyone 10+,Simulation
9945,Ultimate Tennis,SPORTS,4.30,183004,100.00,"10,000,000",Free,0,Everyone,Sports
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [84]:
df_any_paid = df_apps_clean.sort_values(by='Reviews', ascending=False).head(50)
df_any_paid[df_any_paid.Price > 0]

TypeError: '>' not supported between instances of 'str' and 'int'

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [ ]:
# Get all the occurrences of Content Ratings
ratings = df_apps_clean.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           6607
Teen                911
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [ ]:
# Creating an graph object
fig = express.pie(labels=ratings.index, values=ratings.values, title="Content Rating", names=ratings.index)
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

In [ ]:
# Creating a Donut 🍩🍩
fig = express.pie(labels=ratings.index, values=ratings.values, title="Content Rating", names=ratings.index, hole=0.6)
fig.update_traces(textposition='inside', textfont_size=15, textinfo='percent')
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [ ]:
# How many apps had over 1 billion (that's right - BILLION) installations? 
# How many apps just had a single install?

df_installations = df_apps_clean[['Installs', 'App']].groupby('Installs').count()
print(f"N. installations billion: {df_installations[df_installations.index == 1_000_000_000]}")
print(f"N. installations 1: {df_installations[df_installations.index == 1]}")

N. installations billion:             App
Installs
1000000000   20
N. installations 1:           App
Installs
1           3

In [ ]:
# To check the data types you can either use .describe() on the column or .info() 
# on the DataFrame.
df_apps_clean.info()
df_apps_clean.Installs.describe()

<class 'pandas.DataFrame'>
Index: 8184 entries, 21 to 10835
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               8184 non-null   str
 1   Category          8184 non-null   str
 2   Rating            8184 non-null   float64
 3   Reviews           8184 non-null   int64
 4   Size_MBs          8184 non-null   float64
 5   Installs          8184 non-null   int64
 6   Type              8184 non-null   str
 7   Price             8184 non-null   float64
 8   Content_Rating    8184 non-null   str
 9   Genres            8184 non-null   str
 10  Revenue_Estimate  8184 non-null   float64
dtypes: float64(4), int64(2), str(5)
memory usage: 767.2 KB

count           8,184.00
mean        9,186,103.03
std        58,301,373.66
min                 1.00
25%            10,000.00
50%           100,000.00
75%         1,000,000.00
max     1,000,000,000.00
Name: Installs, dtype: float64

In [ ]:
# Count the number of apps at each level of installations.
# 1st. approach
df_ins = df_apps_clean.Installs.value_counts()

# If we take two of the columns, say Installs and the App name, we can count the number of 
# entries per level of installations with .groupby() and .count()
# 2nd. approach
df_apps_clean[['App', 'Installs']].groupby('Installs').count()

             App
Installs
1              3
5              9
10            69
50            56
100          302
500          199
1000         694
5000         422
10000        983
50000        456
100000      1095
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

In [ ]:
# Convert the number of installations (the Installs column) to a numeric data type. 
# Hint: this is a 2-step process. You'll have to make sure you remove non-numeric 
# characters first.

df_apps_clean.Installs = df_apps_clean.Installs.astype(str).str.replace(',', "")
df_apps_clean.Installs = pd.to_numeric(df_apps_clean.Installs)
df_apps_clean[['App', 'Installs']].groupby('Installs').count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         698
5000         425
10000        988
50000        457
100000      1096
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [ ]:
# Convert the price column to numeric data. 
df_apps_clean.Price = df_apps_clean.Price.astype(str).str.replace('$', '')
df_apps_clean.Price = pd.to_numeric(df_apps_clean.Price)

# Then investigate the top 20 most expensive apps in the dataset.
df_apps_clean.sort_values(by='Price', ascending=False).head(20)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical,"79,990.00"
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical,"3,999.00"
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle,"37,990.00"
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical,"33,990.00"
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education,299.90
2463,PTA Content Master,MEDICAL,4.20,64,41.00,1000,Paid,29.99,Everyone,Medical,"29,990.00"
2207,EMT PASS,MEDICAL,3.40,51,2.40,1000,Paid,29.99,Everyone,Medical,"29,990.00"
4264,Golfshot Plus: Golf GPS,SPORTS,4.10,3387,25.00,50000,Paid,29.99,Everyone,Sports,"1,499,500.00"
4772,Human Anatomy Atlas 2018: Complete 3D Human Body,MEDICAL,4.50,2921,25.00,100000,Paid,24.99,Everyone,Medical,"2,499,000.00"
3241,"Muscle Premium - Human Anatomy, Kinesiology, B...",MEDICAL,4.20,168,25.00,10000,Paid,24.99,Everyone,Medical,"249,900.00"
2293,Hospitalist Handbook,MEDICAL,4.80,12,18.00,1000,Paid,19.99,Everyone,Medical,"19,990.00"
4470,DRAGON QUEST VIII,FAMILY,4.50,7812,27.00,50000,Paid,19.99,Everyone 10+,Role Playing,"999,500.00"
526,USMLE Step 2 CK Flashcards,FAMILY,5.00,1,40.00,10,Paid,19.99,Everyone,Education,199.90
2119,NewTek NDI,PHOTOGRAPHY,3.50,77,1.20,1000,Paid,19.99,Everyone,Photography,"19,990.00"
2473,boattheory.ch Full 2018,FAMILY,4.70,54,50.00,1000,Paid,19.40,Everyone,Education,"19,400.00"
4090,I am Rich Premium Plus,FINANCE,4.60,459,2.00,10000,Paid,18.99,Everyone,Finance,"189,900.00"
3778,The World Ends With You,GAME,4.60,4108,13.00,10000,Paid,17.99,Everyone 10+,Arcade,"179,900.00"
1508,SkyTest BU/GU Lite,BUSINESS,2.90,28,20.00,500,Paid,17.99,Everyone,Business,"8,995.00"
3439,Trine 2: Complete Story,GAME,3.80,252,11.00,10000,Paid,16.99,Teen,Action,"169,900.00"
2603,2017 EMRA Antibiotic Guide,MEDICAL,4.40,12,3.80,1000,Paid,16.99,Everyone,Medical,"16,990.00"

### The most expensive apps sub $250

In [ ]:
# Remove all apps that cost more than $250 from the df_apps_clean DataFrame.
df_apps_clean[df_apps_clean.Price > 250].value_counts()
df_apps_clean = df_apps_clean.drop(df_apps_clean[df_apps_clean['Price'] > 250].index)
df_apps_clean.sort_values(by='Price', ascending=False).head()

# or....
# df_apps_clean = df_apps_clean[df_apps_clean.Price < 250]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical,"79,990.00"
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical,"3,999.00"
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle,"37,990.00"
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical,"33,990.00"
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education,299.90

### Highest Grossing Paid Apps (ballpark estimate)

In [ ]:
# Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app 
# times the number of installs. What are the top 10 highest-grossing paid apps according to this 
# estimate? Out of the top 10, how many are games?

df_apps_clean['Revenue_Estimate'] = df_apps_clean.Installs.mul(df_apps_clean.Price)
df_apps_clean.sort_values(by='Revenue_Estimate', ascending=False)[:10]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
9220,Minecraft,FAMILY,4.50,2376564,19.00,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,"69,900,000.00"
8825,Hitman Sniper,GAME,4.60,408292,29.00,10000000,Paid,0.99,Mature 17+,Action,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,4.40,348962,26.00,1000000,Paid,6.99,Mature 17+,Action,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,4.40,49553,48.00,1000000,Paid,5.99,Everyone,Photography,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,4.50,23966,0.85,1000000,Paid,5.99,Everyone,Lifestyle,"5,990,000.00"
6594,DraStic DS Emulator,GAME,4.60,87766,12.00,1000000,Paid,4.99,Everyone,Action,"4,990,000.00"
6082,Weather Live,WEATHER,4.50,76593,4.75,500000,Paid,5.99,Everyone,Weather,"2,995,000.00"
6746,Card Wars - Adventure Time,FAMILY,4.30,129603,23.00,1000000,Paid,2.99,Everyone 10+,Card;Action & Adventure,"2,990,000.00"
7633,Five Nights at Freddy's,GAME,4.60,100805,50.00,1000000,Paid,2.99,Teen,Action,"2,990,000.00"
7954,Bloons TD 5,FAMILY,4.60,190086,94.00,1000000,Paid,2.99,Everyone,Strategy,"2,990,000.00"

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [ ]:
# We can find the number of different categories like so:
print(df_apps_clean.Category.nunique())

33

In [ ]:
# To calculate the number of apps per category we can use our old friend .value_counts()
top_10_apps = df_apps_clean.Category.value_counts()[:10]
top_10_apps

Category
FAMILY             1606
GAME                910
TOOLS               719
PRODUCTIVITY        301
PERSONALIZATION     298
LIFESTYLE           297
FINANCE             296
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [ ]:
# To visualise this data in a bar chart we can use the plotly express (our px) bar() function:
bar = express.bar(x=top_10_apps.index, y=top_10_apps.values)
bar.show()

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [ ]:
# But what if we look at it from a different perspective? What matters is not just the 
# total number of apps in the category but how often apps are downloaded in that category. 
# This will give us an idea of how popular a category is. First, we have to group all our 
# apps by category and sum the number of installations:

category_installs = df_apps_clean.groupby(by='Category').agg({'Installs': pd.Series.sum})
category_installs.sort_values(by='Installs', ascending=True, inplace=True)
category_installs

                        Installs
Category
EVENTS                  15949410
BEAUTY                  26916200
PARENTING               31116110
MEDICAL                 39162676
COMICS                  44931100
LIBRARIES_AND_DEMO      52083000
AUTO_AND_VEHICLES       53129800
HOUSE_AND_HOME          97082000
ART_AND_DESIGN         114233100
DATING                 140912410
FOOD_AND_DRINK         211677750
EDUCATION              352852000
WEATHER                361096500
FINANCE                455249400
MAPS_AND_NAVIGATION    503267560
LIFESTYLE              503611120
BUSINESS               692018120
SPORTS                1096431465
HEALTH_AND_FITNESS    1134006220
SHOPPING              1400331540
PERSONALIZATION       1532352930
BOOKS_AND_REFERENCE   1665791655
ENTERTAINMENT         2113660000
NEWS_AND_MAGAZINES    2369110650
TRAVEL_AND_LOCAL      2894859300
VIDEO_PLAYERS         3916897200
FAMILY                4437554490
PHOTOGRAPHY           4649143130
SOCIAL                5487841475
PRODUCTIVITY          5788070180
TOOLS                 8099724500
COMMUNICATION        11039241530
GAME                 13858762717

In [ ]:
horizontal_bar = express.bar(x=category_installs.Installs, y=category_installs.index, orientation='h', title='Category Popularity')
horizontal_bar.update_layout(xaxis_title='Number of Downloads', yaxis_title='Category')
horizontal_bar.show()

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [ ]:
# Create a DataFrame that has the number of apps in one column and the number of installs in another:
app_installs = df_apps_clean.groupby(by='Category').agg({'App': pd.Series.count, 'Installs': pd.Series.sum})
app_installs.sort_values(by='Installs', ascending=False, inplace=True)
app_installs.head()
# app_installs.shape

               App     Installs
Category
GAME           910  13858762717
COMMUNICATION  257  11039241530
TOOLS          719   8099724500
PRODUCTIVITY   301   5788070180
SOCIAL         203   5487841475

In [ ]:
# Another way to solve the code above:
# First, we need to work out the number of apps in each category (similar to what we did previously).
# cat_number = df_apps_clean.groupby('Category').agg({'App': pd.Series.count})
# 
# Then we can use .merge() and combine the two DataFrames.
# cat_merged_df = pd.merge(cat_number, category_installs, on='Category', how="inner")
# print(f'The dimensions of the DataFrame are: {cat_merged_df.shape}')
# cat_merged_df.sort_values('Installs', ascending=False)

In [ ]:
# Then use the plotly express examples from the documentation alongside the .scatter() 
# API reference to create scatter plot that looks like the chart above.

sc = express.scatter(data_frame=app_installs, x=app_installs.App, y=app_installs.Installs, title='Category Concentration', color='Installs', size='App', hover_name=app_installs.index )
sc.update_layout(xaxis_title="Number of Apps (Lower=More Concentrated)", yaxis=dict(type='log'))
sc.show()

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [ ]:
# How many different types of genres are there?
len(df_apps_clean.Genres.unique())

114

In [ ]:
# Can an app belong to more than one genre? 
df_uniques_genres = df_apps_clean.Genres.unique()
df_uniques_genres

<StringArray>
[                              'Medical',
                                'Arcade',
                                'Sports',
                              'Business',
                     'Books & Reference',
                                'Social',
                                 'Tools',
                             'Education',
                         'Communication',
                         'Entertainment',
 ...
                 'Parenting;Brain Games',
                   'Strategy;Creativity',
                   'Arcade;Pretend Play',
   'Health & Fitness;Action & Adventure',
 'Video Players & Editors;Music & Video',
                  'Casual;Music & Video',
                       'Tools;Education',
              'Role Playing;Brain Games',
                   'Adventure;Education',
                'Lifestyle;Pretend Play']
Length: 114, dtype: str

In [ ]:
# Check what happens when you use .value_counts() on a column with nested values?
df_apps_clean.Genres.value_counts().sort_values(ascending=True)[:5]

Genres
Adventure;Education                  1
Lifestyle;Pretend Play               1
Travel & Local;Action & Adventure    1
Art & Design;Pretend Play            1
Communication;Creativity             1
Name: count, dtype: int64

In [ ]:
# We somehow need to separate the genre names to get a clear picture. 
# This is where the string’s .split() method comes in handy. 
# After we’ve separated our genre names based on the semi-colon, 
# we can add them all into a single column with .stack() and then use .value_counts().

stack = df_apps_clean.Genres.str.split(';', expand=True).stack()
print(f"single column with genres: \n{stack}")
print(f"shape: \n{stack.shape}")
num_genres = stack.value_counts()
print(f"length of stack: {len(num_genres)}")

single column with genres:
21     0             Medical
       1                 NaN
28     0              Arcade
       1                 NaN
47     0              Arcade
                  ...
10829  1                 NaN
10831  0    News & Magazines
       1                 NaN
10835  0              Arcade
       1                 NaN
Length: 16398, dtype: str
shape:
(16398,)
length of stack: 53

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

In [ ]:
# bar = express.bar(x=top_10_apps.index, y=top_10_apps.values)
bar = express.bar(x=num_genres.index[:15], y=num_genres.values[:15],  
                title='Top Genres',
                hover_name=num_genres.index[:15],
                color=num_genres.values[:15],
                color_continuous_scale='Agsunset' )
bar.update_layout(xaxis_title='Genres', yaxis_title='Number of Apps', coloraxis_showscale=False)
bar.show()

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [ ]:
# Now that we’ve looked at the total number of apps per category and the total 
# number of apps per genre, let’s see what the split is between free and paid apps.

df_apps_clean.Type.value_counts()

Type
Free    7595
Paid     604
Name: count, dtype: int64

In [ ]:
# We see that the majority of apps are free on the Google Play Store. 
# But perhaps some categories have more paid apps than others. 
# Let’s investigate. We can group our data first by Category and then by Type. 
# Then we can add up the number of apps per each type. Using as_index=False 
# we push all the data into columns rather than end up with our Categories as the index.

df_free_vs_paid = df_apps_clean.groupby(['Category', 'Type'], as_index=False).agg({'App':pd.Series.count})
df_free_vs_paid

             Category  Type  App
0      ART_AND_DESIGN  Free   58
1      ART_AND_DESIGN  Paid    3
2   AUTO_AND_VEHICLES  Free   72
3   AUTO_AND_VEHICLES  Paid    1
4              BEAUTY  Free   42
..                ...   ...  ...
56   TRAVEL_AND_LOCAL  Paid    8
57      VIDEO_PLAYERS  Free  144
58      VIDEO_PLAYERS  Paid    4
59            WEATHER  Free   65
60            WEATHER  Paid    7

[61 rows x 3 columns]

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

In [ ]:
bar = express.bar(df_free_vs_paid,
                  x=df_free_vs_paid.Category, 
                  y=df_free_vs_paid.App,
                  title='Free vs Paid Apps by Category',
                  color='Type',
                  barmode='group')
bar.update_layout(xaxis_title='Category',
                  yaxis_title='Number of Apps',
                  xaxis={'categoryorder':'total descending'},
                  yaxis=dict(type='log'))

bar.add_trace(graph_objects.Bar(
    x=df_free_vs_paid.Category,
    y=df_free_vs_paid[df_free_vs_paid.App == 'Free'],
    name='Type=Free',
    marker_color='indianred'
))
bar.add_trace(graph_objects.Bar(
    x=df_free_vs_paid.Category,
    y=df_free_vs_paid[df_free_vs_paid.App == 'Paid'],
    name='Type=Paid',
    marker_color='lightsalmon'
))

bar.update_xaxes(categoryorder='total descending')
bar.show()

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

In [ ]:
# df_free_vs_paid = df_apps_clean.groupby(['Category', 'Type'], as_index=False).agg({'App':pandas.Series.count})
box = express.box(df_apps_clean,
             y='Installs',
             x='Type',
             color='Type',
             notched=True,
             points='all',
             title='How Many Downloads are Paid Apps Giving Up?')
 
box.update_layout(yaxis=dict(type='log'))
 
box.show()

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

In [86]:
df_paid_apps = df_apps_clean[df_apps_clean['Type'] == 'Paid']
box = express.box(df_paid_apps, 
             x='Category', 
             y='Revenue_Estimate',
             title='How Much Can Paid Apps Earn?')
 
box.update_layout(xaxis_title='Category',
                  yaxis_title='Paid App Ballpark Revenue',
                  xaxis={'categoryorder':'min ascending'},
                  yaxis=dict(type='log'))
 
 
box.show()

ValueError: Value of 'y' is not the name of a column in 'data_frame'. Expected one of ['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type', 'Price', 'Content_Rating', 'Genres'] but received: Revenue_Estimate

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.

In [87]:
box = express.box(df_paid_apps,
             x='Category',
             y="Price",
             title='Price per Category')
 
box.update_layout(xaxis_title='Category',
                  yaxis_title='Paid App Price',
                  xaxis={'categoryorder':'max descending'},
                  yaxis=dict(type='log'))
 
box.show()